exclude_paths: ["news/index.html", "events/index.html"]
title: LIS Jekyll Theme
subtitle: A theme for building biological information systems with Jekyll

# configure styling
sass:
    sass_dir: _sass
    style: compressed

# UIkit theme customization
style:
    link_color: '#0071B3'
    link_hover_color: '#018fe2'
    primary_background: '#87a96b'
    invert_navbar_text: true
    font_size: 15px
    xxlarge_font_size: 38px
    xlarge_font_size: 30px
    large_font_size: 24px
    medium_font_size: 20px
    small_font_size: 14px
    font_family: ProximaNova, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif

# install Jekyll plugins required by the theme
plugins:
  - jekyll-datapage-generator

# LIS Web Components
web_components_version: 1.0.0

# configure the jekyll-datapage-generator plugin
page_gen:
  - data: taxon_list
    template: taxon
    dir: taxa
    name: genus
    index_files: true
    debug: true

# shows posts (i.e. news and events) with a date after the date the site was built on
future: true

# the default number of items shown in card widgets
card_item_limit: 3
