exclude_paths: ["news/index.html", "events/index.html"]
title: LIS Jekyll Theme
subtitle: A theme for building biological information systems with Jekyll

# configure styling
sass:
    sass_dir: _sass
    style: compressed

# UIkit theme customization
style:
    invert_navbar_text: true

# install Jekyll plugins required by the theme
plugins:
  - jekyll-datapage-generator

# LIS Web Components
web_components_version: 1.3.0

# configure the jekyll-datapage-generator plugin
page_gen:
  - data: taxon_list
    template: taxon
    dir: taxa
    name: genus
    index_files: true
    debug: true

# shows posts (i.e. news and events) with a date after the date the site was built on
future: true

# the default number of items shown in card widgets
card_item_limit: 3

# the GraphQL Server URI; LIS by default
graphql_uri: https://graphql.lis.ncgr.org/
